### ISSUE TITLE
would it be possible to remove retweets?

### ISSUE THREAD

**Issue by epictetito** [stritti/bot_sarcoidosis#1]
Hi friend. I'm working on your code and it works like a wonder, thanks for sharing.

One question, besides retweet and favorite ... would it be possible with JAvascript and modifying this code to delete / remove retweets? I'm looking everywhere and I can't find any information about it!

Thanks a lot

**Comment by stritti** [comment]
Hi @epictetito
sorry for my late answer. You can not remove retweets of other users.
I just copied sources and adapted from https://github.com/neojato/T-Hawk
